
# Start window numbering at 1
set -g base-index 1

# Enable vi-mode
set-window-option -g mode-keys vi

# Enable mouse
set -g mouse on

# Set theme
set -g @themepack 'basic'

# Enable focus events for gitgutter
set -g focus-events on

# Increase scroll back
set-option -g history-limit 3000

# Colors
set -g default-terminal 'screen-256color'
set -ga terminal-overrides ',screen-256color:Tc'

bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'jimeh/tmux-themepack'

run -b '~/.tmux/plugins/tpm/tpm'
