format = """
$directory\
$git_branch\
$env_var\
$sudo\
$line_break\
$jobs\
$battery\
$status\
$shell\
$character"""

right_format = """
$git_commit\
"""

[character]
success_symbol = '[λ](bold green) '
error_symbol = '[✗](bold red) '
