format = """
$username\
$hostname\
$localip\
$directory\
$git_branch\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$guix_shell\
$nix_shell\
$env_var\
$sudo\
$line_break\
$jobs\
$battery\
$status\
$shell\
$character"""

right_format = """
$git_commit\
$cmd_duration\
"""

[character]
success_symbol = '[λ](bold green) '
error_symbol = '[✗](bold red) '
